### ISSUE TITLE
last_run_duration in seconds

### ISSUE THREAD

**Issue by valentusys** [ivanovevgeny/zabbix-mssqlserver-jobs#1]
Hello and thank you!

If you replace the line:
`,ISNULL(STUFF(STUFF(REPLACE(STR([sJSTP].last_run_duration,7,0),' ','0'),4,0,':'),7,0,':'), '') AS 'LAST_RUN_DURATION' `

to:

`,ISNULL(last_run_duration, 0)/10000 ,last_run_duration/100%100 ,last_run_duration%100 ,(last_run_duration/10000 * 60 * 60) + (last_run_duration/100%100 * 60) + (last_run_duration%100 ) AS 'LAST_RUN_DURATION'`

and replace: `$line+= "- mssql.job.info[" + $row.JOB_NAME + ",last_run_duration] '" + $row.LAST_RUN_DURATION + "'`n" `

to:  `$line+= "- mssql.job.info[" + $row.JOB_NAME + ",last_run_duration] " + $row.LAST_RUN_DURATION + "`n" `

in **mssqljobs.ps1**

and change item type to Numeric (unsigned) in discovery item "Job {#JOBNAME} Last Run Duration"
this will allow the duration value in seconds.

**Comment by ivanovevgeny** [comment]
Agree with you, it's more convenient format. 
Changed it  554d37982f050ea345897718a4891b9f7d2c3f6e.
